export default {
  '@react-native-community/async-storage@1.4.2': {
    licenses: 'MIT',
    repository: 'https://github.com/react-native-community/react-native-async-storage',
    licenseUrl: 'https://github.com/react-native-community/react-native-async-storage/raw/master/LICENSE',
    parents: 'sappad',
  },
  '@react-native-community/blur@3.3.1': {
    licenses: 'MIT',
    repository: 'https://github.com/react-native-community/react-native-blur',
    licenseUrl: 'https://github.com/react-native-community/react-native-blur/raw/master/LICENSE',
    parents: 'sappad',
  },
  'd3-shape@1.3.5': {
    licenses: 'BSD-3-Clause',
    repository: 'https://github.com/d3/d3-shape',
    licenseUrl: 'https://github.com/d3/d3-shape/raw/master/LICENSE',
    parents: 'sappad',
  },
  'eslint-import-resolver-node@0.3.2': {
    licenses: 'MIT',
    repository: 'https://github.com/benmosher/eslint-plugin-import',
    licenseUrl: 'https://github.com/benmosher/eslint-plugin-import',
    parents: 'sappad',
  },
  'native-base@2.12.1': {
    licenses: 'Apache-2.0',
    repository: 'https://github.com/GeekyAnts/NativeBase',
    licenseUrl: 'https://github.com/GeekyAnts/NativeBase/raw/master/LICENSE',
    parents: 'sappad',
  },
  'prop-types@15.7.2': {
    licenses: 'MIT',
    repository: 'https://github.com/facebook/prop-types',
    licenseUrl: 'https://github.com/facebook/prop-types/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-autocomplete-input@4.1.0': {
    licenses: 'MIT',
    repository: 'https://github.com/mrlaessig/react-native-autocomplete-input',
    licenseUrl: 'https://github.com/mrlaessig/react-native-autocomplete-input/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-cached-image@1.4.3': {
    licenses: 'MIT',
    repository: 'https://github.com/kfiroo/react-native-cached-image',
    licenseUrl: 'https://github.com/kfiroo/react-native-cached-image/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-camera@2.10.1': {
    licenses: 'MIT AND Apache-2.0 AND BSD-3-Clause',
    repository: 'https://github.com/react-native-community/react-native-camera',
    licenseUrl: 'https://github.com/react-native-community/react-native-camera/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-collapsible@1.4.0': {
    licenses: 'MIT',
    repository: 'git+https://oblador@github.com/oblador/react-native-collapsible',
    licenseUrl: 'git+https://oblador@github.com/oblador/react-native-collapsible/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-elements@1.1.0': {
    licenses: 'MIT',
    repository: 'https://github.com/react-native-training/react-native-elements',
    licenseUrl: 'https://github.com/react-native-training/react-native-elements/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-firebase@5.4.2': {
    licenses: 'Apache-2.0',
    repository: 'https://github.com/invertase/react-native-firebase',
    licenseUrl: 'https://github.com/invertase/react-native-firebase/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-fs@2.13.3': {
    licenses: 'MIT',
    repository: 'https://github.com/itinance/react-native-fs',
    licenseUrl: 'https://github.com/itinance/react-native-fs/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-gesture-handler@1.2.2': {
    licenses: 'MIT',
    repository: 'https://github.com/kmagiera/react-native-gesture-handler',
    licenseUrl: 'https://github.com/kmagiera/react-native-gesture-handler/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-image-picker@0.28.1': {
    licenses: 'MIT',
    repository: 'https://github.com/react-community/react-native-image-picker',
    licenseUrl: 'https://github.com/react-community/react-native-image-picker/raw/master/LICENSE.md',
    parents: 'sappad',
  },
  'react-native-indicators@0.13.0': {
    licenses: 'BSD-3-Clause',
    repository: 'https://github.com/n4kz/react-native-indicators',
    licenseUrl: 'https://github.com/n4kz/react-native-indicators/raw/master/license.txt',
    parents: 'sappad',
  },
  'react-native-link-preview@1.4.2': {
    licenses: 'MIT',
    repository: 'https://github.com/ospfranco/react-native-link-preview',
    licenseUrl: 'https://github.com/ospfranco/react-native-link-preview',
    parents: 'sappad',
  },
  'react-native-picker@4.3.7': {
    licenses: 'MIT',
    repository: 'https://github.com/beefe/react-native-picker',
    licenseUrl: 'https://github.com/beefe/react-native-picker',
    parents: 'sappad',
  },
  'react-native-popup-menu@0.15.6': {
    licenses: 'ISC',
    repository: 'https://github.com/instea/react-native-popup-menu',
    licenseUrl: 'https://github.com/instea/react-native-popup-menu/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-svg@9.4.0': {
    licenses: 'MIT',
    repository: 'https://github.com/react-native-community/react-native-svg',
    licenseUrl: 'https://github.com/react-native-community/react-native-svg/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-vector-icons@6.4.2': {
    licenses: 'MIT',
    repository: 'https://github.com/oblador/react-native-vector-icons',
    licenseUrl: 'https://github.com/oblador/react-native-vector-icons/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native-webview@5.12.0': {
    licenses: 'MIT',
    repository: 'https://github.com/react-native-community/react-native-webview',
    licenseUrl: 'https://github.com/react-native-community/react-native-webview/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-native@0.59.8': {
    licenses: 'MIT',
    repository: 'https://github.com/facebook/react-native',
    licenseUrl: 'https://github.com/facebook/react-native/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react-navigation@3.11.0': {
    licenses: 'BSD-2-Clause',
    repository: 'https://github.com/react-navigation/react-navigation',
    licenseUrl: 'https://github.com/react-navigation/react-navigation/raw/master/LICENSE',
    parents: 'sappad',
  },
  'react@16.8.3': {
    licenses: 'MIT',
    repository: 'https://github.com/facebook/react',
    licenseUrl: 'https://github.com/facebook/react/raw/master/LICENSE',
    parents: 'sappad',
  },
  'shorthash@0.0.2': {
    licenses: 'MIT',
    repository: 'https://github.com/bibig/node-shorthash',
    licenseUrl: 'https://github.com/bibig/node-shorthash/raw/master/LICENSE',
    parents: 'sappad',
  },
  'tflite-react-native@0.0.4': {
    licenses: 'MIT',
    repository: 'https://github.com/shaqian/tflite-react-native',
    licenseUrl: 'https://github.com/shaqian/tflite-react-native/raw/master/LICENSE',
    parents: 'sappad',
  },
};
